# Copyright 2026 Wolf480pl <wolf480@interia.pl>
#
# Modified by Wolf480pl <wolf480@interia.pl>,
# based on luci-proto-gre, which was:
#
#   Based on luci-proto-ipip.
#   Credited author of luci-proto-ipip is Roger Pueyo Centelles <roger.pueyo@guifi.net>
#   Copyright 2016 Roger Pueyo Centelles <roger.pueyo@guifi.net>
#
#   Modified by Jan Betik <jan.betik@svine.su>
#   Copyright 2020 Jan Betik <jan.betik@svine.su>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for BFD (RFC5880)
LUCI_DEPENDS:=+bfdd

PKG_MAINTAINER:=Wolf480pl <wolf480@interia.pl>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
