#!/bin/sh /etc/rc.common

START=90
STOP=15

start()
{
	config_load "chinadns"
	local enabled dns port
	config_get enabled config enabled
	config_get dns config dns
	config_get port config port

	[ $enabled = '0' ] && exit 0

	chinadns \
		-c /etc/chinadns_chnroute.txt \
		-p $port \
		-vv \
		-s "$dns" 2>&1 | logger -t ChinaDNS &
}

stop()
{
	killall -9 chinadns
}
