#!/bin/sh /etc/rc.common
START=79

start() {
	### replace shipped config with symlink
	if [ ! -L /etc/collectd.conf ]; then
		test -f /etc/collectd.conf && mv /etc/collectd.conf /etc/collectd.conf.bak
		ln -s /var/etc/collectd.conf /etc/collectd.conf
	fi

	### create config
	mkdir -p /var/etc
	/usr/bin/stat-genconfig > /var/etc/collectd.conf

	### prepare rrdimg directory
	if [ -f /etc/config/lucid ] && [ -x /etc/init.d/lucid ] && /etc/init.d/lucid enabled && \
	   [ "$(uci get luci_statistics.rrdtool.image_path 2>/dev/null)" != "$(uci get lucid.statistics.physical 2>/dev/null)" ]; then
		uci set lucid.statistics.physical=$(uci get luci_statistics.rrdtool.image_path)
		uci commit lucid
		/etc/init.d/lucid restart
	fi

	### workaround broken permissions on /tmp
	chmod 1777 /tmp
}

restart() {
	### regenerate config / prepare environment
	start

	### restart collectd
	/etc/init.d/collectd restart
}
