#!/bin/sh
uci batch <<-EOF
        set freifunk.community.name='Freifunk Hannover'
        set freifunk.community.homepage=http://www.freifunk-hannover.de
        set freifunk.community.essid=hannover.freifunk.net
        set freifunk.community.bssid=CA:FF:EE:CA:FF:EE
        set freifunk.community.realm=db.freifunk-hannover.de
        set freifunk.community.channel=1
        set freifunk.community.net=10.2.0.0
        set freifunk.community.mask=255.255.0.0
        set luci.main.mediaurlbase=/luci-static/fledermaus
        set luci.main.lang=de
        commit freifunk
        commit luci
EOF
	
