#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for the Polipo Proxy
LUCI_DEPENDS:=+luci-base +luci-compat +polipo

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Aleksandar Krsteski <alekrsteski@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
