# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#
#
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Access Control Configuration
PKG_NAME:=luci-app-accesscontrol
PKG_VERSION:=1.1
PKG_RELEASE=$(PKG_SOURCE_VERSION)
PKG_MAINTAINER:=August Germar <august@anonabox.com>
LUCI_DEPENDS:=

include ../../luci.mk
#
# call BuildPackage - OpenWrt buildroot signature
