#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

NAME=wifihistory
PROG=/usr/sbin/wifihistory
INTERVAL=30

start_service() {
	mkdir -p /var/lib/wifihistory

	procd_open_instance "$NAME"
	procd_set_param command /bin/sh -c "while true; do /usr/bin/ucode $PROG; sleep $INTERVAL; done"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "wireless"
}
