#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# Copyright (C) 2015 GuoGuo <gch981213@gmail.com>
# 
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for kmod-adkill
LUCI_DEPENDS:=+kmod-adkill

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
