include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for externally managed protocol
LUCI_DEPENDS:=+external-protocol

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Oskari Rauta <oskari.rauta@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
