include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for externally managed protocol
LUCI_DEPENDS:=+external-protocol

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
