#
# Copyright (C) 2020 Jo-Philipp Wich <jo@mein.io>
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Simple UI
LUCI_DEPENDS:=+luci-base

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
