#
# Copyright (C) 2020 TDT AG <development@tdt.de>
#
# This is free software, licensed under the Apache License Version 2.0.
# See https://www.apache.org/licenses/LICENSE-2.0 for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for xinetd
LUCI_DEPENDS:=+xinetd
LUCI_PKGARCH:=all

PKG_MAINTAINER:=Helge Mader <ma@dev.tdt.de>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
