# supports ddns-scripts 1.0.0-23 and ddns-scripts starting
# PKG_VERSION:=2.0.1
# PKG_RELEASE:=8
# PKG_MAINTAINER:=Christian Schoenebeck <christian.schoenebeck@gmail.com>

PO = ddns

include ../../build/config.mk
include ../../build/module.mk
