#
# Copyright (C) 2015 OpenWrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Squid LuCI Interface
LUCI_DEPENDS:=+luci-base +squid

PKG_MAINTAINER:=Marko Ratkaj <marko.ratkaj@sartura.hr>, \
	Daniel Nilsson <dannil+github@protonmail.com>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
