#!/bin/sh /etc/rc.common

START=79
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/uwsgi --ini /etc/uwsgi/sites/luci.ini
	procd_set_param file /etc/uwsgi/sites/luci.ini
	procd_set_param respawn
	procd_close_instance
	} 
