#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Coova Chilli
LUCI_DEPENDS:=+luci-base +coova-chilli

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Steven Barth <steven@midlink.org>, \
	Jo-Philipp Wich <jo@mein.io>, \
	Paul Donald <newtwen+github@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
