#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for XFRM interfaces
LUCI_DEPENDS:=+xfrm

PKG_MAINTAINER:=Glen Huang <heyhgl@gmail.com>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
