#
# Copyright 2020 Wojciech Jowsa <wojciech.jowsa@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for Virtual eXtensible Local Area Network (VXLAN, RFC7348)
LUCI_DEPENDS:=+vxlan

PKG_MAINTAINER:=Wojciech Jowsa <wojciech.jowsa@gmail.com>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
