#
# Copyright (C) 2026 OpenWrt.org
#
# This is free software, licensed under Apache-2.0.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-plugin-pwpolicy

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Christian Korber <ckorber@tdt.de>
PKG_DESCRIPTION:=LuCI Password Policy Plugin

LUCI_TITLE:=LuCI Password Policy Plugin
LUCI_DEPENDS:=+luci-base

LUCI_TYPE:=plugin

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot
