#!/bin/sh

case "$1" in
	installed)
		cat /usr/lib/opkg/status
	;;
	available)
		lists_dir=$(sed -rne 's#^lists_dir \S+ (\S+)#\1#p' /etc/opkg.conf /etc/opkg/*.conf 2>/dev/null | tail -n 1)
		find "${lists_dir:-/tmp/opkg-lists}" -type f '!' -name '*.sig' | xargs -r gzip -cd
	;;
	*)
		echo "Usage: $0 {installed|available}" >&2
		exit 1
	;;
esac
