#
# Copyright (C) 2008-2020 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for OpenFortivpn
LUCI_DEPENDS:=+openfortivpn +luci-lua-runtime

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
