#
# Copyright (C) 2008-2020 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for OpenFortivpn
LUCI_DEPENDS:=+openfortivpn +luci-base

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Aaron Goodman <aaronjg@stanford.edu>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
