# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for the Thread border router protocol
LUCI_DEPENDS:=+openthread-br

PKG_MAINTAINER:=Christian Glombek <c.glombek@cosa.systems>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
