#
# Copyright (C) 2015 OpenWrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Roaring Penguin PPPoE Server
LUCI_DEPENDS:=+luci-base +rp-pppoe-server

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Paul Donald <newtwen+github@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
