#
# Copyright (C) 2023 kulupu.io development team (turretkeeper@kulupu.io)
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for Yggdrasil Network
LUCI_DEPENDS:=+yggdrasil
LUCI_PKGARCH:=all
PKG_VERSION:=1.1.1
PKG_MAINTAINER:=William Fleurant <meshnet@protonmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
