include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for modem network mode switching
LUCI_DEPENDS:=+luci-base +comgt
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-3.0-or-later
PKG_MAINTAINER:=devopenm <devopenm@proton.me>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
