#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=OLSR configuration and status module
LUCI_DEPENDS:=+luci-base +olsrd

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Manuel Munz <munz@comuno.net>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
