# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=UCI Git Backup
LUCI_DEPENDS:=+luci-base +uci-git-backup

PKG_LICENSE:=GPL-2.0-only
PKG_MAINTAINER:=Mathias Rangger <mathias.rangger@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
