#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mmc_over_gpio[-1]
	add ucitrack mmc_over_gpio
	set ucitrack.@mmc_over_gpio[-1].init=mmc_over_gpio
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
