# Copyright 2023 Puran Lyu <pl2355@nyu.edu>
# This is free software, licensed under the Apache License, Version 2.0.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for irqbalance
LUCI_DEPENDS:=+luci-base +irqbalance

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Puran Lyu <pl2355@nyu.edu>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
