#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Softether management application
LUCI_DEPENDS:=+softethervpn5-client

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
