#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Softether management application
LUCI_DEPENDS:=+luci-base +softethervpn5-client

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=BERENYI Balazs <balazs@wee.hu>, \
	Jo-Philipp Wich <jo@mein.io>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
