#!/bin/sh
tables="/etc/iproute2/rt_tables"
[ -z "`grep -q "gw-check" $tables`" ] && echo "200 gw-check" >> $tables
test -f /etc/crontabs/root || touch /etc/crontabs/root
[ -z "`grep -q "ff_olsr_test_gw.sh" /etc/crontabs/root`" ] && echo "* * * * *	/usr/sbin/ff_olsr_test_gw.sh" >> /etc/crontabs/root
/etc/init.d/cron restart
