# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_MAINTAINER:=Toke Høiland-Jørgensen <toke@toke.dk>
PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=LuCI Support for SQM Scripts
LUCI_DESCRIPTION:=Luci interface for the SQM scripts queue management package
LUCI_DEPENDS:=+luci-base +sqm-scripts

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
