#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# 
# This is free software, licensed under the Apache License, Version 2.0 .
# 
# move to luci app by Gray

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for SQM-Scripts
LUCI_DEPENDS:=lua luci-base +sqm-scripts

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
