#
# Copyright (C) 2019 EWSI
#
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Dual Channel Wi-Fi AP Daemon configuration module
LUCI_DEPENDS:=+luci-base +dcwapd

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Carey Sonsino <csonsino@gmail.com>, \
	Paul Donald <newtwen+github@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
