#
# Copyright 2019-2023 sirpdboy 
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Kucat Theme by sirpdboy
THEME_NAME:=kucat
PKG_NAME:=luci-theme-$(THEME_NAME)
LUCI_DEPENDS:= +curl
PKG_VERSION:=2.3.9
PKG_RELEASE:=20231219

include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
