#
# Copyright (C) 2019-2023 The Sirpdboy Team <herboy2008@gmail.com>    
#
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Kucat Theme
PKG_NAME:=luci-theme-kucat
LUCI_DEPENDS:=
PKG_VERSION:=2.3.9

include ../../luci.mk


# call BuildPackage - OpenWrt buildroot signature
