include $(TOPDIR)/rules.mk

LUCI_TITLE:=LibreSpeed internet speed measurements
LUCI_DEPENDS:=+luci-base +librespeed-common

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Josef Schlehofer <pepe.schlehofer@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
