include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-smart-reboot
LUCI_TITLE:=LuCI support for smart-reboot
LUCI_DEPENDS:=+smart-reboot
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Min Choi <3387910@naver.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
