#
# Copyright (C) 2024 Paul Donald <newtwen@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=p910nd - Printer server module
LUCI_DEPENDS:=+luci-base +luci-compat +p910nd

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
