#
# Copyright (C) 2024 Paul Donald <newtwen@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=p910nd - Printer server module
LUCI_DEPENDS:=+luci-base +p910nd

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Paul Donald <newtwen@gmail.com>, \
	Jo-Philipp Wich <jo@mein.io>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
