#
# Copyright (C) 2022 OpenWrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=p910nd - Printer server module
LUCI_DEPENDS:=+luci-compat +p910nd +kmod-usb-printer

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
