#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#
include $(TOPDIR)/rules.mk

PKG_NAME:=luci-mod-cname

LUCI_TYPE:=mod
LUCI_BASENAME:=cname

LUCI_TITLE:=LuCI DnsMasq cname Administration
LUCI_DEPENDS:=+luci-mod-network

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
