#
# Copyright (C) 2022 Roland Barenbrug <roland@treslong.com>
#
# This is free software, licensed under the Apache License, Version 2.0
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LUCI DSL spectrum graph
LUCI_DEPENDS:=+luci-base +ltq-dsl-base

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
