#
# Copyright (C) 2022 TDT AG <development@tdt.de>
#
# This is free software, licensed under the Apache License Version 2.0.
# See https://www.apache.org/licenses/LICENSE-2.0 for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for LoRaWAN basicstation
LUCI_DEPENDS:=+luci-base +basicstation

PKG_MAINTAINER:=Marcus Schref <mschref@tdt.de>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
