# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Watchcat
LUCI_DEPENDS:=+watchcat

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
