# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Watchcat
LUCI_DEPENDS:=+luci-base +watchcat

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Jo-Philipp Wich <jo@mein.io>, \
	Nicholas Smith <nicholas@nbembedded.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
