# SPDX-License-Identifier: MIT
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Starlink Status Dashboard
LUCI_DEPENDS:=+luci-base +rpcd +starlink-dish

PKG_MAINTAINER:=Mike Eiberg <eiberg.michael@gmail.com>
PKG_LICENSE:=MIT

include ../../luci.mk
