#!/bin/sh

changed=0

set_opt() {
	local key=$1
	local val=$2

	if ! uci -q get "luci.themes.$key" 2>/dev/null; then
		uci set "luci.themes.$key=$val"
		changed=1
	fi
}

set_opt Bootstrap /luci-static/bootstrap
set_opt BootstrapDark /luci-static/bootstrap-dark
set_opt BootstrapLight /luci-static/bootstrap-light

if [ "$PKG_UPGRADE" != 1 ]; then
	uci set luci.main.mediaurlbase=/luci-static/bootstrap
	changed=1
fi

if [ $changed = 1 ]; then
	uci commit luci
fi

exit 0
