# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for vnStat 2
LUCI_DEPENDS:=+luci-base +luci-lib-jsonc +vnstat2 +vnstati2

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Jan Hoffmann <jan@3e8.eu>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
