--[[
LuCI - Lua Configuration Interface
Version definition - do not edit this file
]]--

module "luci.version"

distname    = "Host System"
distversion = "SDK"

luciname    = "LuCI"
luciversion = "SVN"
