#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Material >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Material=/luci-static/material
		set luci.main.mediaurlbase=/luci-static/material
		commit luci
	EOF
fi

exit 0
