# Copyright 2026 Dirk Brenken (dev@brenken.org)
# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for shunt
LUCI_DEPENDS:=+luci-base +shunt

PKG_VERSION:=0.1.5
PKG_RELEASE:=3
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Dirk Brenken <dev@brenken.org>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
