# See /LICENSE for more information.
# This is free software, licensed under the Apache License, Version 2.0 .
#
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for email server configuration (EmailRelay)
LUCI_DEPENDS:=+luci-base +emailrelay
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Sergey Ponomarev <stokito@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
