include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Shadowsocks Rust
LUCI_DEPENDS:=+luci-base +shadowsocks-rust-config

PKG_MAINTAINER:=Jove Yu <yushijun110@gmail.com>
PKG_LICENSE:=GPL-3.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
