#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Universal Plug and Play (UPnP IGD) & PCP/NAT-PMP configuration module
LUCI_DEPENDS:=+luci-base +miniupnpd +rpcd-mod-ucode

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
