# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2023 ImmortalWrt.org

include $(TOPDIR)/rules.mk

PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=LuCI app for AList
LUCI_DEPENDS:=+alist

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
