# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Eventcat
LUCI_DEPENDS:=+luci-base +eventcat

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Nicholas Smith <nicholas@nbembedded.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
