#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for dump1090
LUCI_DEPENDS:=+luci-base +dump1090

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Alvaro Fernandez Rojas <noltari@gmail.com> \
		Paul Donald <newtwen+github@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
