#
# Copyright (C) 2026 André Valentin
#
# This is free software, licensed under the GNU General Public License v2.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Modem status and settings pages for the wwand connection manager
LUCI_DEPENDS:=+wwand +luci-base
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0-only
PKG_MAINTAINER:=André Valentin <avalentin@marcant.net>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
