include $(TOPDIR)/rules.mk

PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=Netlink based bandwidth accounting
LUCI_DEPENDS:=+luci-base +luci-lib-chartjs +nlbwmon

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Jo-Philipp Wich <jo@mein.io>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
