include $(TOPDIR)/rules.mk

PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=Netlink based bandwidth accounting
LUCI_DEPENDS:=+luci-base +luci-lib-chartjs +nlbwmon

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
