#
# Copyright (C) 2017 Yousong Zhou <yszhou4tech@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for shadowsocks-libev
LUCI_DEPENDS:=+luci-base

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Yousong Zhou <yszhou4tech@gmail.com>, \
	Jian Chang <aa65535@live.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
