name: 🪄 Feature request 🧙 🦄
description: Ask for something nice
title: "Feature request: <summary>"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask for something nice!
  - type: textarea
    id: what-i-want
    attributes:
      label: What would you like to see in luci?
      description: feature request
      placeholder: Describe away
      value:
    validations:
      required: true
