name: Something else❓
description: Some other topic
title: Subject
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contact us!
  - type: textarea
    id: issue
    attributes:
      label: How can we otherwise help?
      placeholder: Describe away
      value:
    validations:
      required: true
