#
# Copyright (C) 2022 Jaymin Patel <jem.patel@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for the Apinger
LUCI_DEPENDS:=+luci-base +apinger +apinger-rrd
PKG_LICENSE:=GPL-2.0

PKG_MAINTAINER:=Jaymin Patel <jem.patel@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature

