#!/bin/sh

_=#--[[
export PATH=/usr/sbin:/usr/bin:/sbin:/bin
exec /usr/bin/lua "$0" ${1:+"$@"}
]] _G

require "luci.cacheloader"
require "luci.sgi.cgi"
luci.dispatcher.indexcache = "/tmp/luci-indexcache"
luci.sgi.cgi.run()