# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2024 asvow

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for Tailscale
LUCI_DEPENDS:=+tailscale

PKG_MAINTAINER:=Geoffrey Hall <asvows@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
