#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Rosy >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Rosy=/luci-static/rosy
		set luci.main.mediaurlbase=/luci-static/rosy
		commit luci
	EOF
fi

exit 0
