#
# Copyright (C) 2008-2025
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Unbound Recursive DNS Resolver Configuration
LUCI_DEPENDS:=+luci-base +unbound-daemon

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Eric Luehrsen <ericluehrsen@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
