#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for VTI interfaces
LUCI_DEPENDS:=+vti

PKG_MAINTAINER:=Jaymin Patel <jem.patel@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
