# This is free software, licensed under the MIT License.

include $(TOPDIR)/rules.mk

PKG_LICENSE=MIT

LUCI_TITLE:=µQR - micro QR: SVG QRcode generator JS library

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
