# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for WeeChat IRC client
LUCI_DEPENDS:=+luci-base +weechat +rpcd-mod-ucode

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Josef Schlehofer <pepe.schlehofer@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
