#
# Copyright (C) 2025 OpenWrt.org
#
# This is free software, licensed under Apache-2.0.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for chrony
LUCI_DEPENDS:=+luci-base +chrony-nts

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
