# See /LICENSE for more information.
# This is free software, licensed under the Apache License, Version 2.0 .
#
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for SSH Tunnels (sshtunnel package)

PKG_MAINTAINER:=Sergey Ponomarev <stokito@gmail.com>
LUCI_DEPENDS:=+luci-base +sshtunnel
PKG_VERSION:=1.1.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
