#
# Copyright (C) 2025 OpenWrt LuCI community
#
# This is free software, licensed under the Apache License Version 2.0.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI LED trigger: ping target
LUCI_DESCRIPTION:=LED trigger that indicates reachability of a host (on = reachable, off = unreachable).
LUCI_DEPENDS:=+luci-base

PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=LuCI community <luci@lists.openwrt.org>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
