include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for radsecproxy
LUCI_DEPENDS:=+luci-base +radsecproxy

PKG_MAINTAINER:=Jan-Frederik Rieckers <rieckers@dfn.de>
PKG_LICENSE:=BSD-3-CLAUSE

include ../../luci.mk
