#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI interface to partition and format storage drives
LUCI_DEPENDS:=+fdisk +lsblk +block-mount +mdadm +wipefs

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
