#!/bin/sh

# needed for "Save and Apply" to restart dynapoint
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dynapoint[-1]
	add ucitrack dynapoint
	set ucitrack.@dynapoint[-1].init="dynapoint"
	commit dynapoint
EOF

exit 0
