#
# Copyright (C) 2015 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=uHTTPd Webserver Configuration
LUCI_DEPENDS:=+luci-base +uhttpd

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Daniel Dickinson <openwrt@daniel.thecshore.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
