#!/bin/sh /etc/rc.common
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/luci-httpd
NAME=luci-httpd
DESC="HTTP server"
START=49

test -x $DAEMON || exit 0

set -e

start() {
	echo -n "Starting $DESC: $NAME"
	start-stop-daemon -S -b -q -x $DAEMON
	echo "."
}

stop() {
	echo -n "Stopping $DESC: $NAME"
	start-stop-daemon -K -q -x $DAEMON
	echo "."
}
