#
# Copyright (C) 2021 Florian Eckert <fe@dev.tdt.de>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Notification
LUCI_DESCRIPTION:=Provides the notification indicator in LuCI.

LUCI_DEPENDS:=+system-notification

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature

