#
# Copyright (c) 2018, Tano Systems. All Rights Reserved.
# Anton Kikin <a.kikin@tano-systems.com>
# Copyright (c) 2023-2024. All Rights Reserved.
# Paul Donald <newtwen+github@gmail.com>
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for LLDP daemon
LUCI_DEPENDS:=+lldpd +rpcd-mod-ucode

PKG_LICENSE:=MIT

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
