#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-statistics ) && rm -f /etc/uci-defaults/luci-statistics

	/etc/init.d/luci_statistics enabled || /etc/init.d/luci_statistics enable
	/etc/init.d/collectd enabled || /etc/init.d/collectd enable
	
	exit 0
}
