#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	# luci updates are not in sync with ddns-script updates !!!
	# needed because luci update might delete helper script
	# copy dynamic_dns_helper.tmp.sh from ddns-scripts
	cp -f /usr/lib/ddns/dynamic_dns_lucihelper.tmp.sh /usr/lib/ddns/dynamic_dns_lucihelper.sh

	( . /etc/uci-defaults/luci-ddns ) && rm -f /etc/uci-defaults/luci-ddns
	exit 0
}
