#!/bin/sh /etc/rc.common
START=70

iface_add() {
	local cfg="$1"
	
	config_get zone "$cfg" zone
	[ -n "$zone" ] || return 0
	
	config_get gw "$cfg" gateway
	[ -n "$gw" ] || return 0
	
	iptables -t nat -A zone_${zone}_prerouting -j luci_splash_portal
	
	for i in $gw
	do
		iptables -t nat -A luci_splash_portal -d "$i" -p tcp -m multiport --dports 22,80,443 -j RETURN
	done
}

blacklist_add() {
	local cfg="$1"
	
	config_get mac "$cfg" mac
	[ -n "$mac" ] && iptables -t nat -A luci_splash_portal -m mac --mac-source "$mac" -j DROP
}

whitelist_add() {
	local cfg="$1"
	
	config_get mac "$cfg" mac
	[ -n "$mac" ] && iptables -t nat -A luci_splash_portal -m mac --mac-source "$mac" -j RETURN
}

start() {
	### Read chains from config
	include /lib/network
	scan_interfaces
	config_load luci_splash
	
	### Create subchains
	iptables -t nat -N luci_splash
	iptables -t nat -N luci_splash_portal
	iptables -t nat -N luci_splash_leases
	
	### Build the main and portal rule
	config_foreach blacklist_add blacklist
	config_foreach whitelist_add whitelist
	config_foreach iface_add iface
	
	### Build the portal rule
	iptables -t nat -A luci_splash_portal -p udp --dport 53 -j RETURN
	iptables -t nat -A luci_splash_portal -j luci_splash_leases
	
	### Build the leases rule
	iptables -t nat -A luci_splash_leases -p tcp --dport 80 -j REDIRECT --to-ports 8082
	iptables -t nat -A luci_splash_leases -j DROP
	
	### Start the splash httpd
	start-stop-daemon -S -b -q -x /usr/bin/luci-splashd
}

stop() {	
	### Clear subchains
	iptables -t nat -F luci_splash_leases
	iptables -t nat -F luci_splash_portal
	iptables -t nat -F luci_splash	
	
	### Delete subchains
	iptables -t nat -X luci_splash_leases
	iptables -t nat -X luci_splash_portal
	iptables -t nat -X luci_splash
}

