# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Network Shares - Ksmbd the SMB kernel fileserver
LUCI_DEPENDS:=+luci-base +ksmbd-server

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Richard Yu <yurichard3839@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
