#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Tor Hidden Service
LUCI_DEPENDS:=+tor-hs

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
