#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@shadowsocks-libev[-1]
	add ucitrack shadowsocks-libev
	set ucitrack.@shadowsocks-libev[-1].init=shadowsocks-libev
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
mkdir -p /etc/shadowsocks-libev
/etc/init.d/rpcd reload
exit 0
