#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=OLSR Visualisation
LUCI_DEPENDS:=+luci-base +luci-app-olsr +olsrd +olsrd-mod-txtinfo

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Lorenz Schori <lo@znerol.ch>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
