#!/bin/sh
uci batch <<-EOF
        set freifunk.community.name='Freifunk Leipzig'
        set freifunk.community.homepage=http://leipzig.freifunk.net
        set freifunk.community.essid=leipzig.freifunk.net
        set freifunk.community.bssid=02:CA:FF:EE:BA:BE
        set freifunk.community.realm=db.leipzig.freifunk.net
        set freifunk.community.channel=1
        set freifunk.community.net=104.0.0.0
        set freifunk.community.mask=255.0.0.0
        set freifunk.community.dhcp=10.0.0.0
        set freifunk.community.dhcpmask=255.255.255.0
        set freifunk.community.dns='88.198.178.18 141.54.1.1 212.204.49.83 208.67.220.220 208.67.222.222'
        commit freifunk
EOF
	