#
# Copyright (C) 2018-2020 The Regents of the University of California
#
# This is free software, licensed under the Apache License, Version 2.0 .
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Spoofer LuCI interface
LUCI_DEPENDS:=+luci-compat +luci-mod-admin-full +spoofer

PKG_MAINTAINER:=Ken Keys <kkeys@caida.org>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
