#
# Copyright (C) 2018 The Regents of the University of California
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Spoofer LuCI interface
LUCI_DEPENDS:=+luci-mod-admin-full +spoofer

PKG_MAINTAINER:=Ken Keys <kkeys@caida.org>
PKG_LICENSE:=GPL-3.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
