include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for DAWN
LUCI_DEPENDS:=+dawn +luci-compat +luci-lib-json
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature

