include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for DAWN
LUCI_DEPENDS:=+luci-base +dawn

PKG_MAINTAINER:=Nick Hainke <vincent@systemli.org>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature

