# Copyright 2018 TJ Kolev (tjkolev@gmail.com)
# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Helper API for IoT devices
LUCI_DEPENDS:=+luasec

PKG_MAINTAINER:=TJ Kolev <tjkolev@gmail.com>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature