#
# Copyright (C) 2026
#
# SPDX-License-Identifier: Apache-2.0
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Plugins - HTTP Headers examples and HTTP 2FA UI example
LUCI_DEPENDS:=+luci-base +luci-mod-system

LUCI_TYPE:=plugin

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature

