# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_LICENSE=MIT

LUCI_TITLE:=Simple HTML5 charts using the canvas element

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
