#!/bin/sh
#-- Copyright 2015 Jonathan Bennett <jbennett@incomsystems.biz>
#-- Licensed to the public under the GNU General Public License v2.
. /lib/functions/network.sh

# Clean-up - keytype/hkeytype is unnecessary now
if uci -q show fwknopd | grep \\.h\\?keytype > /dev/null; then
	for keytype in $(uci -q show fwknopd | grep \\.h\\?keytype= | cut -d= -f1); do
		uci delete $keytype
	done
	uci commit fwknopd
fi

# Generate valid keys
if [ "$(uci -q get fwknopd.@access[0].KEY)" = "CHANGEME" ]; then
	uci delete fwknopd.@access[0].KEY
	uci delete fwknopd.@access[0].HMAC_KEY
	uci set fwknopd.@access[0].KEY_BASE64=`fwknopd --key-gen | awk '/^KEY/ {print $2;}'`
	uci set fwknopd.@access[0].HMAC_KEY_BASE64=`fwknopd --key-gen | awk '/^HMAC/ {print $2;}'`
	uci set fwknopd.@config[0].ENABLE_IPT_FORWARDING='y'
	uci set fwknopd.@config[0].ENABLE_NAT_DNS='y'

	uci commit fwknopd
fi

exit 0
