#
# Copyright (C) 2022 Marc Ahlgrim <marc@onemarcfifty.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for the batman-adv protocol
LUCI_DEPENDS:=+kmod-batman-adv

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
