#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-redsocks2 ) && rm -f /etc/uci-defaults/luci-redsocks2
	chmod 755 /etc/init.d/redsocks2 >/dev/null 2>&1
	/etc/init.d/redsocks2 enable >/dev/null 2>&1
	exit 0
}
