include $(TOPDIR)/rules.mk

PKG_NAME:=luci-plugin-csp
PKG_VERSION:=1.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI CSP Plugin - Content Security Policy HTTP header
LUCI_DEPENDS:=+luci-base +luci-mod-system

LUCI_TYPE:=plugin

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
