#
# Copyright (C) 2008-2019 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Yggdrasil
LUCI_DEPENDS:=+luci-base +yggdrasil

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
