#!/bin/sh
PATTERNS='/cgi-bin/luci/admin:root:$p$root /cgi-bin/luci-upload:root:$p$root'

for i in $PATTERNS
do
	grep "$i" ${IPKG_INSTROOT}/etc/httpd.conf >/dev/null 2>/dev/null || echo "$i" >> ${IPKG_INSTROOT}/etc/httpd.conf
done 

[ -n ${IPKG_INSTROOT} ] || /etc/init.d/httpd restart
