#!/bin/sh /etc/rc.common

START=21
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/ledtrig-ping
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "system"
}
