'use strict';
'require view';
'require uci';
'require form';
'require ui';
'require tools.widgets as widgets';

function bridgeName(vid) {
	return 'brvlan' + vid;
}

function findNetworkDevice(name) {
	return uci.sections('network', 'device').find(function(section) {
		return section.name == name;
	});
}

function addUnique(list, value) {
	list = L.toArray(list);

	if (list.indexOf(value) == -1)
		list.push(value);

	return list;
}

function validVid(value) {
	const vid = String(value || '');

	return vid.match(/^\d+$/) && +vid >= 1 && +vid <= 4094;
}

function matchingAccessPoints(section, accessPoints) {
	const ifaces = L.toArray(section.iface);

	/*
	 * netifd treats an empty iface list as applying to all interfaces.
	 * Preserve that behavior here.
	 */
	if (!ifaces.length)
		return Object.keys(accessPoints);

	return ifaces.filter(function(iface) {
		return accessPoints[iface] != null;
	});
}

function prepareDynamicVlanConfiguration() {
	const accessPoints = {};
	const vlanMappings = {};
	const interfaceNames = {};
	const networkMappings = {};
	const vlanByNetwork = {};

	uci.sections('wireless', 'wifi-iface').forEach(function(section) {
		if (section.mode == 'ap')
			accessPoints[section['.name']] = section;
	});

	/*
	 * First inventory all usable wifi-vlan sections.
	 *
	 * Existing configurations are allowed to use:
	 *
	 *   - no iface, meaning all interfaces
	 *   - list iface
	 *   - list network
	 *
	 * Those forms are understood by netifd. We therefore use them when
	 * determining whether an AP has active VLAN mappings, but only perform
	 * topology automation and strict cross-reference validation on the
	 * simple one-AP/one-network form generated by this page.
	 */
	uci.sections('wireless', 'wifi-vlan').forEach(function(section) {
		const vid = String(section.vid || '');
		const ifaces = L.toArray(section.iface);
		const networks = L.toArray(section.network);
		const matchedAps = matchingAccessPoints(section, accessPoints);

		/*
		 * hostapd only emits the VLAN entry when both name and vid exist.
		 */
		if (section.name && validVid(vid)) {
			matchedAps.forEach(function(iface) {
				vlanMappings['%s.%s'.format(iface, vid)] = section;
			});
		}

		/*
		 * Leave global/list-style configurations alone. They are valid
		 * backend configurations, but cannot be represented faithfully by
		 * the simple grid controls on this page.
		 */
		if (ifaces.length != 1 || networks.length != 1)
			return;

		const iface = ifaces[0];
		const networkName = networks[0];

		/*
		 * Do not make an unrelated or stale existing section prevent all
		 * saves from this page.
		 */
		if (!accessPoints[iface] || !validVid(vid))
			return;

		const mappingKey = '%s.%s'.format(iface, vid);
		const interfaceKey = '%s.%s'.format(iface, section.name);

		if (vlanMappings[mappingKey] &&
		    vlanMappings[mappingKey]['.name'] != section['.name'])
			throw new Error(
				_('Access point %s has more than one mapping for VLAN %s.')
					.format(iface, vid)
			);

		if (interfaceNames[interfaceKey])
			throw new Error(
				_('Access point %s uses interface suffix %s more than once.')
					.format(iface, section.name)
			);

		if (!uci.get('network', networkName) ||
		    uci.get('network', networkName, '.type') != 'interface')
			throw new Error(
				_('Dynamic VLAN %s refers to a network which does not exist.')
					.format(section['.name'])
			);

		if (networkMappings[vid] &&
		    networkMappings[vid] != networkName)
			throw new Error(
				_('VLAN %s is assigned to more than one logical network.')
					.format(vid)
			);

		if (vlanByNetwork[networkName] &&
		    vlanByNetwork[networkName] != vid)
			throw new Error(
				_('Network %s is assigned to more than one VLAN ID.')
					.format(networkName)
			);

		vlanMappings[mappingKey] = section;
		interfaceNames[interfaceKey] = section;
		networkMappings[vid] = networkName;
		vlanByNetwork[networkName] = vid;
	});

	/*
	 * A wifi-station entry does not require a VLAN ID. Without vid it is
	 * simply a per-client PPSK on the base network.
	 */
	uci.sections('wireless', 'wifi-station').forEach(function(section) {
		const vid = String(section.vid || '');

		if (!vid)
			return;

		/*
		 * As with wifi-vlan, tolerate list/empty iface forms that are valid
		 * in netifd but cannot be represented by this grid.
		 */
		const ifaces = L.toArray(section.iface);

		if (ifaces.length != 1)
			return;

		const iface = ifaces[0];

		if (!accessPoints[iface])
			return;

		if (!vlanMappings['%s.%s'.format(iface, vid)])
			throw new Error(
				_('PPSK entry %s has no matching Dynamic VLAN for its access point and VLAN ID.')
					.format(section['.name'])
			);
	});

	/*
	 * Prepare the wired topology only for simple mappings managed directly
	 * by this page.
	 */
	Object.keys(networkMappings).forEach(function(vid) {
		const networkName = networkMappings[vid];
		const targetName = bridgeName(vid);
		const configuredDevice = uci.get('network', networkName, 'device');
		const configuredIfname = uci.get('network', networkName, 'ifname');
		const currentName = configuredDevice || configuredIfname;
		let targetDevice = findNetworkDevice(targetName);

		if (!currentName)
			throw new Error(
				_('Network %s needs a device before it can be used for Dynamic VLAN %s.')
					.format(networkName, vid)
			);

		if (targetDevice && targetDevice.type != 'bridge')
			throw new Error(
				_('Device %s already exists but is not a bridge.')
					.format(targetName)
			);

		const currentDevice = findNetworkDevice(currentName);

		/*
		 * If the logical network already uses a bridge, leave it exactly
		 * where it is. netifd can attach the generated wireless VLAN
		 * interface to that existing logical network.
		 *
		 * Most importantly, do not rename or delete an existing bridge.
		 */
		if (currentDevice && currentDevice.type == 'bridge')
			return;

		/*
		 * The network already references the desired bridge name but the
		 * corresponding device section does not exist. Creating that
		 * missing bridge is safe and does not mutate another bridge.
		 */
		if (currentName == targetName) {
			if (!targetDevice) {
				const deviceSid = uci.add('network', 'device');

				uci.set('network', deviceSid, 'name', targetName);
				uci.set('network', deviceSid, 'type', 'bridge');
			}

			return;
		}

		/*
		 * Refuse to alter a pre-existing target bridge that is not already
		 * carrying this device. It may have bridge-vlan sections, VLAN
		 * subdevices, legacy users, or other dependencies which cannot be
		 * safely inferred here.
		 */
		if (targetDevice) {
			const ports = L.toArray(targetDevice.ports);

			if (ports.indexOf(currentName) == -1)
				throw new Error(
					_('Bridge %s already exists and will not be modified automatically. Configure the network to use that bridge manually or choose a different topology.')
						.format(targetName)
				);

			/*
			 * The bridge already contains the required device, so merely
			 * point this logical network at it. No bridge membership is
			 * changed.
			 */
			uci.set('network', networkName, 'device', targetName);
			uci.unset('network', networkName, 'ifname');
			return;
		}

		/*
		 * No bridge exists and the network currently uses a non-bridge
		 * device. Create a new bridge around that device. This is the one
		 * topology transformation this page owns.
		 */
		const deviceSid = uci.add('network', 'device');

		uci.set('network', deviceSid, 'name', targetName);
		uci.set('network', deviceSid, 'type', 'bridge');
		uci.set('network', deviceSid, 'ports', [ currentName ]);

		uci.set('network', networkName, 'device', targetName);
		uci.unset('network', networkName, 'ifname');
	});
}

function apLabel(section) {
	const ssid = section.ssid || _('unnamed SSID');
	const radio = section.device || _('unknown radio');

	return '%s (%s, %s)'.format(ssid, section['.name'], radio);
}

return view.extend({
	load() {
		return Promise.all([
			uci.load('wireless'),
			uci.load('network')
		]);
	},

	render() {
		let m, s, o;

		const accessPoints =
			uci.sections('wireless', 'wifi-iface').filter(function(section) {
				return section.mode == 'ap';
			});

		m = new form.Map(
			'wireless',
			_('Dynamic VLANs'),
			_('Configure PPSK assignments and dynamic VLAN mappings. Existing bridges are preserved. When a logical network does not already use a bridge, LuCI can create a brvlan<VLAN ID> bridge around its current device.')
		);

		m.chain('network');

		const mapSave = m.save;

		m.save = function(callback, silent) {
			return mapSave.call(this, function() {
				prepareDynamicVlanConfiguration();

				if (typeof(callback) == 'function')
					return callback();
			}, silent);
		};

		/*
		 * Explicit AP-level dynamic VLAN control.
		 */
		s = m.section(
			form.GridSection,
			'wifi-iface',
			_('Dynamic VLAN mode'),
			_('Set the dynamic VLAN mode explicitly for each access point.')
		);

		s.anonymous = true;
		s.addremove = false;
		s.nodescriptions = true;

		s.cfgsections = function() {
			return accessPoints.map(function(section) {
				return section['.name'];
			});
		};

		o = s.option(form.DummyValue, '_ap', _('Access point'));

		o.textvalue = function(sectionId) {
			const section = uci.get('wireless', sectionId);

			return section ? apLabel(section) : sectionId;
		};

		o = s.option(
			form.ListValue,
			'dynamic_vlan',
			_('Dynamic VLAN mode')
		);

		o.value('0', _('Disabled'));
		o.value('1', _('Optional'));
		o.value('2', _('Required'));
		o.default = '0';
		o.rmempty = true;
		o.editable = true;
		o.onchange = function(ev, sectionId, value) {
			const row = ev.target.closest('tr');
			const button = row ? row.querySelector('.cbi-button-save') : null;

			if (button)
				button.disabled = false;
		};
		o.write = function(sectionId, value) {
			return this.super('write', [
				sectionId,
				(value == '0') ? null : value
			]);
		};

		s.renderRowActions = function(sectionId) {
			return E('td', {
				'class': 'td cbi-section-table-cell nowrap cbi-section-actions'
			}, E('div', {}, [
				E('button', {
					'type': 'button',
					'class': 'btn cbi-button cbi-button-save',
					'title': _('Save all pending changes on this Dynamic VLANs page'),
					'disabled': true,
					'click': L.bind(function(ev) {
						return this.map.save(null, false).then(function() {
							ui.showModal(_('Changes saved'), [
								E('p', {}, [
									_('The changes have been staged but are not active yet.')
								]),
								E('p', {}, [
									_('Press "Save & Apply" to apply the pending changes.')
								]),
								E('div', { 'class': 'right' }, [
									E('button', {
										'type': 'button',
										'class': 'btn cbi-button cbi-button-neutral',
										'click': ui.hideModal
									}, [ _('OK') ])
								])
							]);
						});
					}, this)
				}, [ _('Save changes') ])
			]));
		};

		/*
		 * VLAN mappings.
		 */
		s = m.section(
			form.GridSection,
			'wifi-vlan',
			_('Dynamic VLAN mappings'),
			_('Map a VLAN ID on an access point to an existing logical network. Existing bridges are reused without being renamed or deleted.')
		);

		s.anonymous = true;
		s.addremove = true;
		s.sortable = true;
		s.nodescriptions = true;
		s.addbtntitle = _('Add Dynamic VLAN');
		s.handleRemove = function(sectionId, ev) {
			uci.remove('wireless', sectionId);

			return this.map.save(null, false);
		};
		o = s.option(
			form.ListValue,
			'iface',
			_('Access point')
		);

		o.rmempty = false;

		accessPoints.forEach(function(section) {
			o.value(section['.name'], apLabel(section));
		});

		o = s.option(
			form.Value,
			'vid',
			_('VLAN ID')
		);

		o.rmempty = false;
		o.datatype = 'and(uinteger,range(1,4094))';
		o.placeholder = '53';

		o = s.option(
			form.Value,
			'name',
			_('Interface suffix'),
			_('Short unique name used for the generated wireless VLAN interface, for example iot.')
		);

		o.rmempty = false;
		o.datatype = 'uciname';
		o.placeholder = 'iot';

		o = s.option(
			widgets.NetworkSelect,
			'network',
			_('Network'),
			_('Existing logical network carrying this VLAN. If it already uses a bridge, that bridge is preserved. Otherwise a new brvlan<VLAN ID> bridge may be created around its current device.')
		);

		o.rmempty = false;
		o.nocreate = true;
		o.loopback = false;

		o = s.option(
			form.Flag,
			'bridge_isolate',
			_('Isolate bridge clients'),
			_('Prevent direct forwarding between clients attached to the dynamic VLAN bridge.')
		);

		o.modalonly = true;
		o.default = o.disabled;

		/*
		 * PPSK assignments.
		 */
		s = m.section(
			form.GridSection,
			'wifi-station',
			_('PPSK assignments'),
			_('Each entry assigns a password, optionally restricted to one client MAC address. VLAN ID is optional; without it the private password remains on the access point base network. Use 00:00:00:00:00:00 for a password available to any client.')
		);

		s.anonymous = true;
		s.addremove = true;
		s.sortable = true;
		s.nodescriptions = true;
		s.addbtntitle = _('Add PPSK');
		s.handleRemove = function(sectionId, ev) {
			uci.remove('wireless', sectionId);

			return this.map.save(null, false);
		};
		o = s.option(
			form.ListValue,
			'iface',
			_('Access point')
		);

		o.rmempty = false;

		accessPoints.forEach(function(section) {
			o.value(section['.name'], apLabel(section));
		});

		o = s.option(
			form.Value,
			'vid',
			_('VLAN ID'),
			_('Optional. Leave empty to use this private password on the access point base network.')
		);

		o.rmempty = true;
		o.datatype = 'and(uinteger,range(1,4094))';
		o.placeholder = _('base network');

		o = s.option(
			form.Value,
			'mac',
			_('Client MAC address')
		);

		o.rmempty = false;
		o.datatype = 'macaddr';
		o.default = '00:00:00:00:00:00';

		o = s.option(
			form.Value,
			'key',
			_('Private password')
		);

		o.rmempty = false;
		o.datatype = 'wpakey';
		o.password = true;
		o.modalonly = true;

		return m.render();
	}
});
