# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

PKG_LICENSE:=GPL-2.0
PKG_MAINTAINER:=Abdulkader Alrezej <alrazj.abdulkader@gmail.com>

LUCI_TITLE:=LuCI support for Accel-PPP
LUCI_DESCRIPTION:=Provides a LuCI configuration interface for Accel-PPP.
LUCI_DEPENDS:=+luci-base +accel-ppp

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
