--[[
LuCI - Autogenerated Zoneinfo Module

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

]]--

module "luci.sys.zoneinfo"

TZ = {
	{ 'Africa/Abidjan', 'GMT0' },
	{ 'Africa/Accra', 'GMT0' },
	{ 'Africa/Addis Ababa', 'EAT-3' },
	{ 'Africa/Algiers', 'CET-1' },
	{ 'Africa/Asmara', 'EAT-3' },
	{ 'Africa/Bamako', 'GMT0' },
	{ 'Africa/Bangui', 'WAT-1' },
	{ 'Africa/Banjul', 'GMT0' },
	{ 'Africa/Bissau', 'GMT0' },
	{ 'Africa/Blantyre', 'CAT-2' },
	{ 'Africa/Brazzaville', 'WAT-1' },
	{ 'Africa/Bujumbura', 'CAT-2' },
	{ 'Africa/Casablanca', 'WET0' },
	{ 'Africa/Ceuta', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Africa/Conakry', 'GMT0' },
	{ 'Africa/Dakar', 'GMT0' },
	{ 'Africa/Dar es Salaam', 'EAT-3' },
	{ 'Africa/Djibouti', 'EAT-3' },
	{ 'Africa/Douala', 'WAT-1' },
	{ 'Africa/El Aaiun', 'WET0' },
	{ 'Africa/Freetown', 'GMT0' },
	{ 'Africa/Gaborone', 'CAT-2' },
	{ 'Africa/Harare', 'CAT-2' },
	{ 'Africa/Johannesburg', 'SAST-2' },
	{ 'Africa/Kampala', 'EAT-3' },
	{ 'Africa/Khartoum', 'EAT-3' },
	{ 'Africa/Kigali', 'CAT-2' },
	{ 'Africa/Kinshasa', 'WAT-1' },
	{ 'Africa/Lagos', 'WAT-1' },
	{ 'Africa/Libreville', 'WAT-1' },
	{ 'Africa/Lome', 'GMT0' },
	{ 'Africa/Luanda', 'WAT-1' },
	{ 'Africa/Lubumbashi', 'CAT-2' },
	{ 'Africa/Lusaka', 'CAT-2' },
	{ 'Africa/Malabo', 'WAT-1' },
	{ 'Africa/Maputo', 'CAT-2' },
	{ 'Africa/Maseru', 'SAST-2' },
	{ 'Africa/Mbabane', 'SAST-2' },
	{ 'Africa/Mogadishu', 'EAT-3' },
	{ 'Africa/Monrovia', 'GMT0' },
	{ 'Africa/Nairobi', 'EAT-3' },
	{ 'Africa/Ndjamena', 'WAT-1' },
	{ 'Africa/Niamey', 'WAT-1' },
	{ 'Africa/Nouakchott', 'GMT0' },
	{ 'Africa/Ouagadougou', 'GMT0' },
	{ 'Africa/Porto-Novo', 'WAT-1' },
	{ 'Africa/Sao Tome', 'GMT0' },
	{ 'Africa/Tripoli', 'EET-2' },
	{ 'Africa/Tunis', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Africa/Windhoek', 'WAT-1WAST,M9.1.0,M4.1.0' },
	{ 'America/Adak', 'HAST10HADT,M3.2.0,M11.1.0' },
	{ 'America/Anchorage', 'AKST9AKDT,M3.2.0,M11.1.0' },
	{ 'America/Anguilla', 'AST4' },
	{ 'America/Antigua', 'AST4' },
	{ 'America/Araguaina', 'BRT3' },
	{ 'America/Argentina/Buenos Aires', 'ART3ARST,M10.3.0/0,M3.3.0/0' },
	{ 'America/Argentina/Catamarca', 'ART3' },
	{ 'America/Argentina/Cordoba', 'ART3ARST,M10.3.0/0,M3.3.0/0' },
	{ 'America/Argentina/Jujuy', 'ART3' },
	{ 'America/Argentina/La Rioja', 'ART3' },
	{ 'America/Argentina/Mendoza', 'ART3' },
	{ 'America/Argentina/Rio Gallegos', 'ART3' },
	{ 'America/Argentina/Salta', 'ART3' },
	{ 'America/Argentina/San Juan', 'ART3' },
	{ 'America/Argentina/San Luis', 'ART3' },
	{ 'America/Argentina/Tucuman', 'ART3ARST,M10.3.0/0,M3.3.0/0' },
	{ 'America/Argentina/Ushuaia', 'ART3' },
	{ 'America/Aruba', 'AST4' },
	{ 'America/Asuncion', 'PYT4PYST,M10.3.0/0,M3.2.0/0' },
	{ 'America/Atikokan', 'EST5' },
	{ 'America/Bahia', 'BRT3' },
	{ 'America/Barbados', 'AST4' },
	{ 'America/Belem', 'BRT3' },
	{ 'America/Belize', 'CST6' },
	{ 'America/Blanc-Sablon', 'AST4' },
	{ 'America/Boa Vista', 'AMT4' },
	{ 'America/Bogota', 'COT5' },
	{ 'America/Boise', 'MST7MDT,M3.2.0,M11.1.0' },
	{ 'America/Cambridge Bay', 'MST7MDT,M3.2.0,M11.1.0' },
	{ 'America/Campo Grande', 'AMT4AMST,M10.3.0/0,M2.3.0/0' },
	{ 'America/Cancun', 'CST6CDT,M4.1.0,M10.5.0' },
	{ 'America/Caracas', 'VET4:30' },
	{ 'America/Cayenne', 'GFT3' },
	{ 'America/Cayman', 'EST5' },
	{ 'America/Chicago', 'CST6CDT,M3.2.0,M11.1.0' },
	{ 'America/Chihuahua', 'MST7MDT,M4.1.0,M10.5.0' },
	{ 'America/Costa Rica', 'CST6' },
	{ 'America/Cuiaba', 'AMT4AMST,M10.3.0/0,M2.3.0/0' },
	{ 'America/Curacao', 'AST4' },
	{ 'America/Danmarkshavn', 'GMT0' },
	{ 'America/Dawson', 'PST8PDT,M3.2.0,M11.1.0' },
	{ 'America/Dawson Creek', 'MST7' },
	{ 'America/Denver', 'MST7MDT,M3.2.0,M11.1.0' },
	{ 'America/Detroit', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Dominica', 'AST4' },
	{ 'America/Edmonton', 'MST7MDT,M3.2.0,M11.1.0' },
	{ 'America/Eirunepe', 'AMT4' },
	{ 'America/El Salvador', 'CST6' },
	{ 'America/Fortaleza', 'BRT3' },
	{ 'America/Glace Bay', 'AST4ADT,M3.2.0,M11.1.0' },
	{ 'America/Goose Bay', 'AST4ADT,M3.2.0/0:01,M11.1.0/0:01' },
	{ 'America/Grand Turk', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Grenada', 'AST4' },
	{ 'America/Guadeloupe', 'AST4' },
	{ 'America/Guatemala', 'CST6' },
	{ 'America/Guayaquil', 'ECT5' },
	{ 'America/Guyana', 'GYT4' },
	{ 'America/Halifax', 'AST4ADT,M3.2.0,M11.1.0' },
	{ 'America/Havana', 'CST5CDT,M3.3.0/0,M10.5.0/1' },
	{ 'America/Hermosillo', 'MST7' },
	{ 'America/Indiana/Indianapolis', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Indiana/Knox', 'CST6CDT,M3.2.0,M11.1.0' },
	{ 'America/Indiana/Marengo', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Indiana/Petersburg', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Indiana/Tell City', 'CST6CDT,M3.2.0,M11.1.0' },
	{ 'America/Indiana/Vevay', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Indiana/Vincennes', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Indiana/Winamac', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Inuvik', 'MST7MDT,M3.2.0,M11.1.0' },
	{ 'America/Iqaluit', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Jamaica', 'EST5' },
	{ 'America/Juneau', 'AKST9AKDT,M3.2.0,M11.1.0' },
	{ 'America/Kentucky/Louisville', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Kentucky/Monticello', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/La Paz', 'BOT4' },
	{ 'America/Lima', 'PET5' },
	{ 'America/Los Angeles', 'PST8PDT,M3.2.0,M11.1.0' },
	{ 'America/Maceio', 'BRT3' },
	{ 'America/Managua', 'CST6' },
	{ 'America/Manaus', 'AMT4' },
	{ 'America/Marigot', 'AST4' },
	{ 'America/Martinique', 'AST4' },
	{ 'America/Mazatlan', 'MST7MDT,M4.1.0,M10.5.0' },
	{ 'America/Menominee', 'CST6CDT,M3.2.0,M11.1.0' },
	{ 'America/Merida', 'CST6CDT,M4.1.0,M10.5.0' },
	{ 'America/Mexico City', 'CST6CDT,M4.1.0,M10.5.0' },
	{ 'America/Miquelon', 'PMST3PMDT,M3.2.0,M11.1.0' },
	{ 'America/Moncton', 'AST4ADT,M3.2.0,M11.1.0' },
	{ 'America/Monterrey', 'CST6CDT,M4.1.0,M10.5.0' },
	{ 'America/Montevideo', 'UYT3UYST,M10.1.0,M3.2.0' },
	{ 'America/Montreal', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Montserrat', 'AST4' },
	{ 'America/Nassau', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/New York', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Nipigon', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Nome', 'AKST9AKDT,M3.2.0,M11.1.0' },
	{ 'America/Noronha', 'FNT2' },
	{ 'America/North Dakota/Center', 'CST6CDT,M3.2.0,M11.1.0' },
	{ 'America/North Dakota/New Salem', 'CST6CDT,M3.2.0,M11.1.0' },
	{ 'America/Panama', 'EST5' },
	{ 'America/Pangnirtung', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Paramaribo', 'SRT3' },
	{ 'America/Phoenix', 'MST7' },
	{ 'America/Port of Spain', 'AST4' },
	{ 'America/Port-au-Prince', 'EST5' },
	{ 'America/Porto Velho', 'AMT4' },
	{ 'America/Puerto Rico', 'AST4' },
	{ 'America/Rainy River', 'CST6CDT,M3.2.0,M11.1.0' },
	{ 'America/Rankin Inlet', 'CST6CDT,M3.2.0,M11.1.0' },
	{ 'America/Recife', 'BRT3' },
	{ 'America/Regina', 'CST6' },
	{ 'America/Rio Branco', 'AMT4' },
	{ 'America/Santarem', 'BRT3' },
	{ 'America/Santo Domingo', 'AST4' },
	{ 'America/Sao Paulo', 'BRT3BRST,M10.3.0/0,M2.3.0/0' },
	{ 'America/Scoresbysund', 'EGT1EGST,M3.5.0/0,M10.5.0/1' },
	{ 'America/Shiprock', 'MST7MDT,M3.2.0,M11.1.0' },
	{ 'America/St Barthelemy', 'AST4' },
	{ 'America/St Johns', 'NST3:30NDT,M3.2.0/0:01,M11.1.0/0:01' },
	{ 'America/St Kitts', 'AST4' },
	{ 'America/St Lucia', 'AST4' },
	{ 'America/St Thomas', 'AST4' },
	{ 'America/St Vincent', 'AST4' },
	{ 'America/Swift Current', 'CST6' },
	{ 'America/Tegucigalpa', 'CST6' },
	{ 'America/Thule', 'AST4ADT,M3.2.0,M11.1.0' },
	{ 'America/Thunder Bay', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Tijuana', 'PST8PDT,M4.1.0,M10.5.0' },
	{ 'America/Toronto', 'EST5EDT,M3.2.0,M11.1.0' },
	{ 'America/Tortola', 'AST4' },
	{ 'America/Vancouver', 'PST8PDT,M3.2.0,M11.1.0' },
	{ 'America/Whitehorse', 'PST8PDT,M3.2.0,M11.1.0' },
	{ 'America/Winnipeg', 'CST6CDT,M3.2.0,M11.1.0' },
	{ 'America/Yakutat', 'AKST9AKDT,M3.2.0,M11.1.0' },
	{ 'America/Yellowknife', 'MST7MDT,M3.2.0,M11.1.0' },
	{ 'Antarctica/Casey', 'WST-8' },
	{ 'Antarctica/Davis', 'DAVT-7' },
	{ 'Antarctica/DumontDUrville', 'DDUT-10' },
	{ 'Antarctica/Mawson', 'MAWT-6' },
	{ 'Antarctica/McMurdo', 'NZST-12NZDT,M9.5.0,M4.1.0/3' },
	{ 'Antarctica/Rothera', 'ROTT3' },
	{ 'Antarctica/South Pole', 'NZST-12NZDT,M9.5.0,M4.1.0/3' },
	{ 'Antarctica/Syowa', 'SYOT-3' },
	{ 'Antarctica/Vostok', 'VOST-6' },
	{ 'Arctic/Longyearbyen', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Aden', 'AST-3' },
	{ 'Asia/Almaty', 'ALMT-6' },
	{ 'Asia/Amman', 'EET-2EEST,M3.5.4/0,M10.5.5/1' },
	{ 'Asia/Anadyr', 'ANAT-12ANAST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Aqtau', 'AQTT-5' },
	{ 'Asia/Aqtobe', 'AQTT-5' },
	{ 'Asia/Ashgabat', 'TMT-5' },
	{ 'Asia/Baghdad', 'AST-3' },
	{ 'Asia/Bahrain', 'AST-3' },
	{ 'Asia/Baku', 'AZT-4AZST,M3.5.0/4,M10.5.0/5' },
	{ 'Asia/Bangkok', 'ICT-7' },
	{ 'Asia/Beirut', 'EET-2EEST,M3.5.0/0,M10.5.0/0' },
	{ 'Asia/Bishkek', 'KGT-6' },
	{ 'Asia/Brunei', 'BNT-8' },
	{ 'Asia/Choibalsan', 'CHOT-8' },
	{ 'Asia/Chongqing', 'CST-8' },
	{ 'Asia/Colombo', 'IST-5:30' },
	{ 'Asia/Damascus', 'EET-2EEST,M4.1.5/0,J305/0' },
	{ 'Asia/Dhaka', 'BDT-6' },
	{ 'Asia/Dili', 'TLT-9' },
	{ 'Asia/Dubai', 'GST-4' },
	{ 'Asia/Dushanbe', 'TJT-5' },
	{ 'Asia/Gaza', 'EET-2EEST,J91/0,M8.5.4' },
	{ 'Asia/Harbin', 'CST-8' },
	{ 'Asia/Ho Chi Minh', 'ICT-7' },
	{ 'Asia/Hong Kong', 'HKT-8' },
	{ 'Asia/Hovd', 'HOVT-7' },
	{ 'Asia/Irkutsk', 'IRKT-8IRKST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Jakarta', 'WIT-7' },
	{ 'Asia/Jayapura', 'EIT-9' },
	{ 'Asia/Kabul', 'AFT-4:30' },
	{ 'Asia/Kamchatka', 'PETT-12PETST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Karachi', 'PKT-5' },
	{ 'Asia/Kashgar', 'CST-8' },
	{ 'Asia/Kathmandu', 'NPT-5:45' },
	{ 'Asia/Kolkata', 'IST-5:30' },
	{ 'Asia/Krasnoyarsk', 'KRAT-7KRAST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Kuala Lumpur', 'MYT-8' },
	{ 'Asia/Kuching', 'MYT-8' },
	{ 'Asia/Kuwait', 'AST-3' },
	{ 'Asia/Macau', 'CST-8' },
	{ 'Asia/Magadan', 'MAGT-11MAGST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Makassar', 'CIT-8' },
	{ 'Asia/Manila', 'PHT-8' },
	{ 'Asia/Muscat', 'GST-4' },
	{ 'Asia/Nicosia', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Asia/Novosibirsk', 'NOVT-6NOVST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Omsk', 'OMST-6OMSST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Oral', 'ORAT-5' },
	{ 'Asia/Phnom Penh', 'ICT-7' },
	{ 'Asia/Pontianak', 'WIT-7' },
	{ 'Asia/Pyongyang', 'KST-9' },
	{ 'Asia/Qatar', 'AST-3' },
	{ 'Asia/Qyzylorda', 'QYZT-6' },
	{ 'Asia/Rangoon', 'MMT-6:30' },
	{ 'Asia/Riyadh', 'AST-3' },
	{ 'Asia/Sakhalin', 'SAKT-10SAKST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Samarkand', 'UZT-5' },
	{ 'Asia/Seoul', 'KST-9' },
	{ 'Asia/Shanghai', 'CST-8' },
	{ 'Asia/Singapore', 'SGT-8' },
	{ 'Asia/Taipei', 'CST-8' },
	{ 'Asia/Tashkent', 'UZT-5' },
	{ 'Asia/Tbilisi', 'GET-4' },
	{ 'Asia/Thimphu', 'BTT-6' },
	{ 'Asia/Tokyo', 'JST-9' },
	{ 'Asia/Ulaanbaatar', 'ULAT-8' },
	{ 'Asia/Urumqi', 'CST-8' },
	{ 'Asia/Vientiane', 'ICT-7' },
	{ 'Asia/Vladivostok', 'VLAT-10VLAST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Yakutsk', 'YAKT-9YAKST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Yekaterinburg', 'YEKT-5YEKST,M3.5.0,M10.5.0/3' },
	{ 'Asia/Yerevan', 'AMT-4AMST,M3.5.0,M10.5.0/3' },
	{ 'Atlantic/Azores', 'AZOT1AZOST,M3.5.0/0,M10.5.0/1' },
	{ 'Atlantic/Bermuda', 'AST4ADT,M3.2.0,M11.1.0' },
	{ 'Atlantic/Canary', 'WET0WEST,M3.5.0/1,M10.5.0' },
	{ 'Atlantic/Cape Verde', 'CVT1' },
	{ 'Atlantic/Faroe', 'WET0WEST,M3.5.0/1,M10.5.0' },
	{ 'Atlantic/Madeira', 'WET0WEST,M3.5.0/1,M10.5.0' },
	{ 'Atlantic/Reykjavik', 'GMT0' },
	{ 'Atlantic/South Georgia', 'GST2' },
	{ 'Atlantic/St Helena', 'GMT0' },
	{ 'Atlantic/Stanley', 'FKT4FKST,M9.1.0,M4.3.0' },
	{ 'Australia/Adelaide', 'CST-9:30CST,M10.1.0,M4.1.0/3' },
	{ 'Australia/Brisbane', 'EST-10' },
	{ 'Australia/Broken Hill', 'CST-9:30CST,M10.1.0,M4.1.0/3' },
	{ 'Australia/Currie', 'EST-10EST,M10.1.0,M4.1.0/3' },
	{ 'Australia/Darwin', 'CST-9:30' },
	{ 'Australia/Eucla', 'CWST-8:45' },
	{ 'Australia/Hobart', 'EST-10EST,M10.1.0,M4.1.0/3' },
	{ 'Australia/Lindeman', 'EST-10' },
	{ 'Australia/Lord Howe', 'LHST-10:30LHST-11,M10.1.0,M4.1.0' },
	{ 'Australia/Melbourne', 'EST-10EST,M10.1.0,M4.1.0/3' },
	{ 'Australia/Perth', 'WST-8' },
	{ 'Australia/Sydney', 'EST-10EST,M10.1.0,M4.1.0/3' },
	{ 'Europe/Amsterdam', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Andorra', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Athens', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Belgrade', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Berlin', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Bratislava', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Brussels', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Bucharest', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Budapest', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Chisinau', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Copenhagen', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Dublin', 'GMT0IST,M3.5.0/1,M10.5.0' },
	{ 'Europe/Gibraltar', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Guernsey', 'GMT0BST,M3.5.0/1,M10.5.0' },
	{ 'Europe/Helsinki', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Isle of Man', 'GMT0BST,M3.5.0/1,M10.5.0' },
	{ 'Europe/Istanbul', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Jersey', 'GMT0BST,M3.5.0/1,M10.5.0' },
	{ 'Europe/Kaliningrad', 'EET-2EEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Kiev', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Lisbon', 'WET0WEST,M3.5.0/1,M10.5.0' },
	{ 'Europe/Ljubljana', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/London', 'GMT0BST,M3.5.0/1,M10.5.0' },
	{ 'Europe/Luxembourg', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Madrid', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Malta', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Mariehamn', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Minsk', 'EET-2EEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Monaco', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Moscow', 'MSK-3MSD,M3.5.0,M10.5.0/3' },
	{ 'Europe/Oslo', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Paris', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Podgorica', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Prague', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Riga', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Rome', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Samara', 'SAMT-4SAMST,M3.5.0,M10.5.0/3' },
	{ 'Europe/San Marino', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Sarajevo', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Simferopol', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Skopje', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Sofia', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Stockholm', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Tallinn', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Tirane', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Uzhgorod', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Vaduz', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Vatican', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Vienna', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Vilnius', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Volgograd', 'VOLT-3VOLST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Warsaw', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Zagreb', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Europe/Zaporozhye', 'EET-2EEST,M3.5.0/3,M10.5.0/4' },
	{ 'Europe/Zurich', 'CET-1CEST,M3.5.0,M10.5.0/3' },
	{ 'Indian/Antananarivo', 'EAT-3' },
	{ 'Indian/Chagos', 'IOT-6' },
	{ 'Indian/Christmas', 'CXT-7' },
	{ 'Indian/Cocos', 'CCT-6:30' },
	{ 'Indian/Comoro', 'EAT-3' },
	{ 'Indian/Kerguelen', 'TFT-5' },
	{ 'Indian/Mahe', 'SCT-4' },
	{ 'Indian/Maldives', 'MVT-5' },
	{ 'Indian/Mauritius', 'MUT-4MUST,M10.5.0,M3.5.0/3' },
	{ 'Indian/Mayotte', 'EAT-3' },
	{ 'Indian/Reunion', 'RET-4' },
	{ 'Pacific/Apia', 'WST11' },
	{ 'Pacific/Auckland', 'NZST-12NZDT,M9.5.0,M4.1.0/3' },
	{ 'Pacific/Chatham', 'CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45' },
	{ 'Pacific/Efate', 'VUT-11' },
	{ 'Pacific/Enderbury', 'PHOT-13' },
	{ 'Pacific/Fakaofo', 'TKT10' },
	{ 'Pacific/Fiji', 'FJT-12' },
	{ 'Pacific/Funafuti', 'TVT-12' },
	{ 'Pacific/Galapagos', 'GALT6' },
	{ 'Pacific/Gambier', 'GAMT9' },
	{ 'Pacific/Guadalcanal', 'SBT-11' },
	{ 'Pacific/Guam', 'ChST-10' },
	{ 'Pacific/Honolulu', 'HST10' },
	{ 'Pacific/Johnston', 'HST10' },
	{ 'Pacific/Kiritimati', 'LINT-14' },
	{ 'Pacific/Kosrae', 'KOST-11' },
	{ 'Pacific/Kwajalein', 'MHT-12' },
	{ 'Pacific/Majuro', 'MHT-12' },
	{ 'Pacific/Marquesas', 'MART9:30' },
	{ 'Pacific/Midway', 'SST11' },
	{ 'Pacific/Nauru', 'NRT-12' },
	{ 'Pacific/Niue', 'NUT11' },
	{ 'Pacific/Norfolk', 'NFT-11:30' },
	{ 'Pacific/Noumea', 'NCT-11' },
	{ 'Pacific/Pago Pago', 'SST11' },
	{ 'Pacific/Palau', 'PWT-9' },
	{ 'Pacific/Pitcairn', 'PST8' },
	{ 'Pacific/Ponape', 'PONT-11' },
	{ 'Pacific/Port Moresby', 'PGT-10' },
	{ 'Pacific/Rarotonga', 'CKT10' },
	{ 'Pacific/Saipan', 'ChST-10' },
	{ 'Pacific/Tahiti', 'TAHT10' },
	{ 'Pacific/Tarawa', 'GILT-12' },
	{ 'Pacific/Tongatapu', 'TOT-13' },
	{ 'Pacific/Truk', 'TRUT-10' },
	{ 'Pacific/Wake', 'WAKT-12' },
	{ 'Pacific/Wallis', 'WFT-12' },
}

OFFSET = {
	gmt   =      0,	-- GMT
	eat   =  10800,	-- EAT
	cet   =   3600,	-- CET
	wat   =   3600,	-- WAT
	cat   =   7200,	-- CAT
	wet   =      0,	-- WET
	sast  =   7200,	-- SAST
	eet   =   7200,	-- EET
	hast  = -36000,	-- HAST
	hadt  = -32400,	-- HADT
	akst  = -32400,	-- AKST
	akdt  = -28800,	-- AKDT
	ast   = -14400,	-- AST
	brt   = -10800,	-- BRT
	art   = -10800,	-- ART
	arst  =  -7200,	-- ARST
	pyt   = -14400,	-- PYT
	pyst  = -10800,	-- PYST
	est   = -18000,	-- EST
	cst   = -21600,	-- CST
	amt   = -14400,	-- AMT
	cot   = -18000,	-- COT
	mst   = -25200,	-- MST
	mdt   = -21600,	-- MDT
	vet   = -16200,	-- VET
	gft   = -10800,	-- GFT
	pst   = -28800,	-- PST
	pdt   = -25200,	-- PDT
	ect   = -18000,	-- ECT
	gyt   = -14400,	-- GYT
	bot   = -14400,	-- BOT
	pet   = -18000,	-- PET
	pmst  = -10800,	-- PMST
	pmdt  =  -7200,	-- PMDT
	uyt   = -10800,	-- UYT
	uyst  =  -7200,	-- UYST
	fnt   =  -7200,	-- FNT
	srt   = -10800,	-- SRT
	egt   =  -3600,	-- EGT
	egst  =      0,	-- EGST
	nst   = -12600,	-- NST
	ndt   =  -9000,	-- NDT
	wst   =  28800,	-- WST
	davt  =  25200,	-- DAVT
	ddut  =  36000,	-- DDUT
	mawt  =  21600,	-- MAWT
	nzst  =  43200,	-- NZST
	nzdt  =  46800,	-- NZDT
	rott  = -10800,	-- ROTT
	syot  =  10800,	-- SYOT
	vost  =  21600,	-- VOST
	almt  =  21600,	-- ALMT
	anat  =  43200,	-- ANAT
	anast =  46800,	-- ANAST
	aqtt  =  18000,	-- AQTT
	tmt   =  18000,	-- TMT
	azt   =  14400,	-- AZT
	azst  =  18000,	-- AZST
	ict   =  25200,	-- ICT
	kgt   =  21600,	-- KGT
	bnt   =  28800,	-- BNT
	chot  =  28800,	-- CHOT
	ist   =  19800,	-- IST
	bdt   =  21600,	-- BDT
	tlt   =  32400,	-- TLT
	gst   =  14400,	-- GST
	tjt   =  18000,	-- TJT
	hkt   =  28800,	-- HKT
	hovt  =  25200,	-- HOVT
	irkt  =  28800,	-- IRKT
	irkst =  32400,	-- IRKST
	wit   =  25200,	-- WIT
	eit   =  32400,	-- EIT
	aft   =  16200,	-- AFT
	pett  =  43200,	-- PETT
	petst =  46800,	-- PETST
	pkt   =  18000,	-- PKT
	npt   =  20700,	-- NPT
	krat  =  25200,	-- KRAT
	krast =  28800,	-- KRAST
	myt   =  28800,	-- MYT
	magt  =  39600,	-- MAGT
	magst =  43200,	-- MAGST
	cit   =  28800,	-- CIT
	pht   =  28800,	-- PHT
	novt  =  21600,	-- NOVT
	novst =  25200,	-- NOVST
	omst  =  21600,	-- OMST
	omsst =  25200,	-- OMSST
	orat  =  18000,	-- ORAT
	kst   =  32400,	-- KST
	qyzt  =  21600,	-- QYZT
	mmt   =  23400,	-- MMT
	sakt  =  36000,	-- SAKT
	sakst =  39600,	-- SAKST
	uzt   =  18000,	-- UZT
	sgt   =  28800,	-- SGT
	get   =  14400,	-- GET
	btt   =  21600,	-- BTT
	jst   =  32400,	-- JST
	ulat  =  28800,	-- ULAT
	vlat  =  36000,	-- VLAT
	vlast =  39600,	-- VLAST
	yakt  =  32400,	-- YAKT
	yakst =  36000,	-- YAKST
	yekt  =  18000,	-- YEKT
	yekst =  21600,	-- YEKST
	azot  =  -3600,	-- AZOT
	azost =      0,	-- AZOST
	cvt   =  -3600,	-- CVT
	fkt   = -14400,	-- FKT
	fkst  = -10800,	-- FKST
	cwst  =  31500,	-- CWST
	lhst  =  37800,	-- LHST
	lhst  =  39600,	-- LHST
	msk   =  10800,	-- MSK
	msd   =  14400,	-- MSD
	samt  =  14400,	-- SAMT
	samst =  18000,	-- SAMST
	volt  =  10800,	-- VOLT
	volst =  14400,	-- VOLST
	iot   =  21600,	-- IOT
	cxt   =  25200,	-- CXT
	cct   =  23400,	-- CCT
	tft   =  18000,	-- TFT
	sct   =  14400,	-- SCT
	mvt   =  18000,	-- MVT
	mut   =  14400,	-- MUT
	must  =  18000,	-- MUST
	ret   =  14400,	-- RET
	chast =  45900,	-- CHAST
	chadt =  49500,	-- CHADT
	vut   =  39600,	-- VUT
	phot  =  46800,	-- PHOT
	tkt   = -36000,	-- TKT
	fjt   =  43200,	-- FJT
	tvt   =  43200,	-- TVT
	galt  = -21600,	-- GALT
	gamt  = -32400,	-- GAMT
	sbt   =  39600,	-- SBT
	hst   = -36000,	-- HST
	lint  =  50400,	-- LINT
	kost  =  39600,	-- KOST
	mht   =  43200,	-- MHT
	mart  = -34200,	-- MART
	sst   = -39600,	-- SST
	nrt   =  43200,	-- NRT
	nut   = -39600,	-- NUT
	nft   =  41400,	-- NFT
	nct   =  39600,	-- NCT
	pwt   =  32400,	-- PWT
	pont  =  39600,	-- PONT
	pgt   =  36000,	-- PGT
	ckt   = -36000,	-- CKT
	taht  = -36000,	-- TAHT
	gilt  =  43200,	-- GILT
	tot   =  46800,	-- TOT
	trut  =  36000,	-- TRUT
	wakt  =  43200,	-- WAKT
	wft   =  43200,	-- WFT
}
