#!/bin/sh
touch /etc/config/arpbind

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@arpbind[-1]
	add ucitrack arpbind
	set ucitrack.@arpbind[-1].exec='/etc/init.d/arpbind restart'
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
