# Copyright 2020 Bogdan Shatik (bogdikxxx@mail.ru)
# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

PKG_MAINTAINER:=Bogdan Shatik <bogdikxxx@mail.ru>
PKG_NAME:=luci-app-eoip
PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=LuCI Support for EoIP
LUCI_DEPENDS:=+eoip +luci-base

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
