#
# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Aria2
LUCI_DEPENDS:=+aria2

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature

