#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for  qos_gargoyle
LUCI_DEPENDS:=+qos-gargoyle

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
#applications/luci-app-qos_gargoyle/
#applications/luci-app-qos_gargoyle/
