add( "admin", "statistics", "Statistiken", 70 )
--act( "apache", "Apache" )
--act( "apcups", "Apcups" )
--act( "ascent", "Ascent" )
--act( "cpufreq", "Cpufreq" )
act( "csv", "CSV" )
act( "df", "Speicher" )
act( "disk", "Festplatte" )
act( "dns", "DNS" )
act( "email", "E-Mail" )
act( "exec", "Exec" )
act( "interface", "Schnittstellen" )
act( "iptables", "Firewall" )
act( "irq", "Interrupts" )
act( "logfile", "Protokolldateien" )
act( "netlink", "Netlink" )
act( "network", "Netzwerk" )
--act( "nginx", "nginx Server" )
--act( "ntpd", "NTP Server" )
act( "ping", "Ping" )
--act( "powerdns", "Powerdns Server" )
--act( "processes", "Prozesse" )
--act( "rrdtool", "RRD Tool" )
--act( "sensors", "Sensoren" )
--act( "snmp", "SNMP Datenquellen" )
--act( "syslog", "Systemlog" )
--act( "tail", "Dateiverfolgung" )
--act( "teamspeak2", "TeamSpeak 2" )
--act( "tcpconns", "TCP Verbindungen" )
--act( "unixsock", "UNIX Sockets" )
--act( "vmem", "Vmem" )
