#
# Copyright (C) 2010 OpenWrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=CrowdSec firewall bouncer LuCI interface
LUCI_DEPENDS:=+luci-base +crowdsec-firewall-bouncer

PKG_MAINTAINER:=S. Brusch <ne20002@gmx.ch>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
