#
# Copyright (C) 2010 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=ACME package - LuCI interface
LUCI_DEPENDS:=+luci-base +acme

PKG_MAINTAINER:=Toke Høiland-Jørgensen <toke@toke.dk>
PKG_LICENSE:=GPL-3.0-or-later

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
