# SPDX-License-Identifier: GPL-2.0-or-later
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for ifwatchdog
LUCI_DEPENDS:=+ifwatchdog
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0-or-later
PKG_MAINTAINER:=one7two99

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
