# Copyright 2026 Julius Bairaktaris <julius@bairaktaris.de>
# Licensed to the public under the Apache License 2.0.

include $(TOPDIR)/rules.mk

PKG_MAINTAINER:=Julius Bairaktaris <julius@bairaktaris.de>
PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=LuCI support for the Qualcomm PPE hardware QoS classifiers
LUCI_DEPENDS:=+ppe-qos
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
