include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for babeld
LUCI_DEPENDS:=+luci-base +babeld

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Nick Hainke <vincent@systemli.org>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
