include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for babeld
LUCI_DEPENDS:=+luci-base +babeld +luci-compat
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
