#!/bin/sh
uci batch <<-EOF
        set freifunk.community.name='Freifunk Augsburg'
        set freifunk.community.homepage=http://augsburg.freifunk.net
        set freifunk.community.essid=augsburg.freifunk.net
        set freifunk.community.bssid=02:CA:FF:EE:BA:BE
        set freifunk.community.channel=1
        set freifunk.community.net=191.161.0.0
        set freifunk.community.mask=255.255.0.0
        set freifunk.community.dns='88.198.178.18 141.54.1.1 212.204.49.83 208.67.220.220 208.67.222.222'
        set luci.main.mediaurlbase=/luci-static/fledermaus
        set luci.main.lang=de
        commit freifunk
        commit luci
EOF
	
