#
# Copyright (C) 2008-2026 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=uStreamer service configuration module
LUCI_DEPENDS:=+luci-base +ustreamer

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Georgi Valkov <gvalkov@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
