#!/bin/sh

# register commit handler
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci_collectd[-1]
	add ucitrack luci_collectd
	set ucitrack.@luci_collectd[-1].init=luci_collectd
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
