#!/bin/sh

# register commit handler
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci_statistics[-1]
	add ucitrack luci_statistics
	set ucitrack.@luci_statistics[-1].init=luci_statistics
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
