#
# Copyright (C) 2008-2017 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Serial to network module
LUCI_DEPENDS:=+ser2net

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
