#
# Copyright (C) 2020 Michele Primavera
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for ser2net
LUCI_DEPENDS:=+luci-base +ser2net

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Michele Primavera <primavera@elmod.it>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
