#!/bin/sh
uci batch <<-EOF
        set freifunk.community.name='Freifunk Berlin'
        set freifunk.community.homepage=http://berlin.freifunk.net
        set freifunk.community.essid=olsr.freifunk.net
        set freifunk.community.bssid=02:CA:FF:EE:BA:BE
        set freifunk.community.channel=10
        set freifunk.community.net=104.0.0.0
        set freifunk.community.mask=255.0.0.0
        set freifunk.community.dns='88.198.178.18 141.54.1.1 212.204.49.83 208.67.220.220 208.67.222.222'
        set luci.main.mediaurlbase=/luci-static/fledermaus
        set luci.main.lang=de
        commit freifunk
        commit luci
EOF
	
