#
# Copyright (C) 2022 Hannu Nyman <hannu.nyman@iki.fi>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for unetd VPN
LUCI_DEPENDS:=+unetd +unet-cli
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
