#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=QoS over Nftables
LUCI_DEPENDS:=+luci-base +luci-compat +nft-qos

PKG_MAINTAINER:=Rosy Song <rosysong@rosinson.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
