#
# Based on luci-proto-ipip.
# Credited author of luci-proto-ipip is Roger Pueyo Centelles <roger.pueyo@guifi.net>
# Copyright 2016 Roger Pueyo Centelles <roger.pueyo@guifi.net>
#
# Modified by Jan Betik <jan.betik@svine.su>
# Copyright 2020 Jan Betik <jan.betik@svine.su>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for GRE tunnels (RFC2784)
LUCI_DEPENDS:=+gre

PKG_MAINTAINER:=Jan Betik <jan.betik@svine.su>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
