#!/bin/sh /etc/rc.common
# Freifunk Init
# $Id$

START=99

boot() {
	grep -q 'killall -HUP dnsmasq' /etc/crontabs/root || {
		echo "*/5 * * * *	killall -HUP dnsmasq" >> /etc/crontabs/root
	}

	[ -f /etc/rc.local ] && . /etc/rc.local
}
