# Copyright 2019 Olivier Poitrey (rs@nextdns.io)
# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for NextDNS
LUCI_DEPENDS:=+luci-base +nextdns

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Olivier Poitrey <rs@nextdns.io>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
