#!/bin/sh

uci -q get mwan3.globals >/dev/null || {
	uci -q add mwan3 globals >/dev/null
	uci -q rename mwan3.@globals[-1]="globals" >/dev/null
	uci -q set mwan3.globals.local_source="none" >/dev/null
	uci commit mwan3
}

exit 0
