#
# Copyright (C) 2015 OpenWrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=ClamAV LuCI interface
LUCI_DEPENDS:=+luci-base +clamav

PKG_MAINTAINER:=Marko Ratkaj <marko.ratkaj@sartura.hr>\
		Paul Donald <newtwen+github@gmail.com>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
