#!/bin/sh
. /etc/functions.sh

trap '' INT
trap '' TERM
trap '' PIPE

# initialize defaults
RAMFS_COPY_BIN="/usr/bin/awk"       # extra programs for temporary ramfs root
RAMFS_COPY_DATA=""      # extra data files
export KEEP_PATTERN=""
export VERBOSE=1

# parse options
while [ -n "$1" ]; do
        case "$1" in
                -k)
                		shift
				export SAVE_CONFIG=1
                		export KEEP_PATTERN="$1"
                ;;
                -*)
                        echo "Invalid option: $1"
                        exit 1
                ;;
                *) break;;
        esac
        shift;
done

export CONFFILES=/tmp/sysupgrade.conffiles
export CONF_TAR=/tmp/sysupgrade.tgz

[ -f $CONFFILES ] && rm $CONFFILES
[ -f $CONF_TAR ]  && rm $CONF_TAR

export ARGV="$*"
export ARGC="$#"

[ -z "$ARGV" ] && {
        cat <<EOF
Usage: $0 [options] <image file or URL>

Options:
        -k	<"file 1, file 2, ...">	Files to be kept
EOF
        exit 1
}

add_pattern_conffiles() {
	local file="$1"
	find $KEEP_PATTERN >> "$file" 2>/dev/null
	return 0
}

# hooks
sysupgrade_image_check="platform_check_image"
sysupgrade_init_conffiles=""

[ -n "$KEEP_PATTERN" ] && append sysupgrade_init_conffiles "add_pattern_conffiles"

include /lib/upgrade

do_save_conffiles() {
        [ -z "$(rootfs_type)" ] && {
                echo "Cannot save config while running from ramdisk."
                exit 3
                return 0
        }
        run_hooks "$CONFFILES" $sysupgrade_init_conffiles

        v "Saving config files..."
        [ "$VERBOSE" -gt 1 ] && TAR_V="v" || TAR_V=""
        tar c${TAR_V}zf "$CONF_TAR" -T "$CONFFILES" 2>/dev/null
}

type platform_check_image >/dev/null 2>/dev/null || {
        echo "Firmware upgrade is not implemented for this platform."
        exit 1
}

for check in $sysupgrade_image_check; do
        ( eval "$check \"\$ARGV\"" ) || {
                echo "Image check '$check' failed."
                exit 2
        }
done

[ -n "$sysupgrade_init_conffiles" ] && do_save_conffiles
run_hooks "" $sysupgrade_pre_upgrade

if [ -n "$(rootfs_type)" ]; then
	v "Switching to ramdisk..."
	run_ramfs '. /etc/functions.sh; include /lib/upgrade; do_upgrade'
else
	do_upgrade
fi
