# Copyright 2017-2025 Dirk Brenken (dev@brenken.org)
# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Adblock
LUCI_DEPENDS:=+luci-base +adblock

PKG_VERSION:=4.4.5
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Dirk Brenken <dev@brenken.org>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
