# Copyright 2026 Benoit M
# Licensed to the public under the GPL-2.0-or-later.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for the LED matrix controller
LUCI_DEPENDS:=+luci-base +ledmatrixd

PKG_MAINTAINER:=Benoit Masson <benoitm974@users.noreply.github.com>
PKG_LICENSE:=GPL-2.0-or-later
include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
