#
# Copyright (C) 2020 Robert Koszewski <rkkoszewski@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for SSTP
LUCI_DEPENDS:=+sstp-client
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Robert Koszewski <rkkoszewski@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
