#
# Copyright (C) 2019 harveyhu2012
# Copyright (C) 2019 Robert Koszewski <rkkoszewski@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for SSTP
LUCI_DEPENDS:=+sstp-client
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature