# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Network Shares - CIFSD CIFS/SMB kernel fileserver
LUCI_DEPENDS:=+cifsd-tools @BROKEN

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
