#!/bin/sh

. /usr/share/libubox/jshn.sh

action=$1
shift

ipkg_bin="/usr/bin/apk"

# Exit early if apk is missing
[ -x "$ipkg_bin" ] || exit 1

case "$action" in
	list-installed)
		$ipkg_bin query --fields all --format json --installed --from system \* 2>/dev/null
	;;
	list-available)
		$ipkg_bin query --fields all --format json --available \* 2>/dev/null
	;;
	install|update|upgrade|remove)
		(
			case "$action" in
				install) action="add" ;;
				remove)  action="del" ;;
			esac

			# Handle specific apk flags
			cmd="$ipkg_bin"
			while [ -n "$1" ]; do
				case "$1" in
					--autoremove)
						# Just shift and do nothing. 
						# 'apk del' already cleans up orphaned dependencies by default.
						shift
						;;
					--force-removal-of-dependent-packages)
						cmd="$cmd -r"
						shift ;;
					--force-overwrite)
						cmd="$cmd --force-overwrite"
						shift ;;
					*) break ;;
				esac
			done

			if flock -x 200; then
				pkmcmd="$cmd $action $@"
				$cmd $action "$@" </dev/null >/tmp/ipkg.out 2>/tmp/ipkg.err
				code=$?
				stdout=$(cat /tmp/ipkg.out)
				stderr=$(cat /tmp/ipkg.err)
			else
				code=255
				stderr="Failed to acquire lock"
			fi

			json_init
			json_add_int code $code
			[ -n "$pkmcmd" ] && json_add_string pkmcmd "$pkmcmd"
			[ -n "$stdout" ] && json_add_string stdout "$stdout"
			[ -n "$stderr" ] && json_add_string stderr "$stderr"
			json_dump
		) 200>/tmp/ipkg.lock

		rm -f /tmp/ipkg.lock /tmp/ipkg.err /tmp/ipkg.out
	;;
esac