name: Test Build

on:
  pull_request:

jobs:
  build:
    uses: openwrt/actions-shared-workflows/.github/workflows/multi-arch-test-build.yml@main
    with:
      matrix: '{"include": [{"arch": "x86_64", "target": "x86-64"}]}'
