# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Network Shares - Samba 4 SMB/CIFS fileserver
LUCI_DEPENDS:=+luci-base +samba4-server

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Andy Walsh <andy.walsh44+github@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
