#!/bin/sh

# no longer needed for "Save and Apply" to restart ddns
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ddns[-1]
	commit ucitrack
EOF

# make helper script executable
chmod 755 /usr/lib/ddns/dynamic_dns_lucihelper.sh

# update application section for luci-app-ddns
uci -q get ddns.global > /dev/null || uci -q set ddns.global='ddns'
uci -q get ddns.global.date_format > /dev/null || uci -q set ddns.global.date_format='%F %R'
uci -q get ddns.global.log_lines > /dev/null || uci -q set ddns.global.log_lines='250'
uci -q commit ddns

rm -f /tmp/luci-indexcache
exit 0
